---
title: "Molecular secretory and cycle models"
author: "Jessica Chung"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
    toc_depth: 4
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=TRUE, message=TRUE, error=TRUE, echo=TRUE, results="hold")
knitr::opts_knit$set(root.dir = "..")
options(digits=4)
options(width=120)
Sys.setenv(TZ = "Australia/Melbourne")
```

-----

# Load

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(sva)
library(splines)
library(mgcv)
```

```{r}
# qld_counts_list <- readRDS("data/tidy_data/qld_counts_list.rds")
sample_info <- readRDS("data/tidy_data/sample_info.rds")
# all_annotations <- readRDS("data/tidy_data/all_annotations.rds")
# combat_nc <- readRDS("data/tidy_data/batch_normalised_exprs.rds")
hormone_info <- readRDS("data/tidy_data/hormone_info.rds")
```

```{r}
# RNA
dataset_id <- "2021-03-23"
secretory_model_phenotype <- readRDS(sprintf("data/tidy_data/secretory_model_phenotype_%s.rds", dataset_id))
secretory_estimates <- 
  readRDS(sprintf("cache/secretory_model_estimates_%s.rds", dataset_id))

dataset_id <- "2021-03-23"
combat_phenotype <- 
  readRDS(file=sprintf("data/tidy_data/combat_phenotype_%s.rds", dataset_id))

unique_id <- "2021-03-23_k30_g4"
gene_models <- readRDS(sprintf("data/gene_models/gene_models_%s.rds", unique_id))
```


```{r}
# Array
dataset_id <- "2020-12-02"
array_secretory_model_phenotype <-
  readRDS(sprintf("data/tidy_data/array_secretory_model_%s.rds", dataset_id))
array_secretory_estimates <-
  readRDS(sprintf("cache/array_secretory_model_estimates_%s.rds", dataset_id))

dataset_id <- "2020-12-02"
array_combat_phenotype <-
  readRDS(file=sprintf("data/tidy_data/array_combat_phenotype_%s.rds", dataset_id))
```

-----

# RNA-seq model EDA

```{r}
ggplot(combat_phenotype, aes(x=transformed_time_2, y=cycle_stage_reassigned_prolif)) +
  geom_jitter(height=0.1, width=0) +
  scale_y_discrete(limits = factor(c(NA, 7:1))) +
  scale_x_continuous(breaks=seq(0, 100, by=10)) +
  labs(x="Molecular Model Time")

ggplot(combat_phenotype, aes(x=transformed_time_2, y=new_cycle_stage)) +
  geom_jitter(height=0.1, width=0) +
  scale_y_discrete(limits = factor(c(NA, 7:1))) +
  scale_x_continuous(breaks=seq(0, 100, by=10)) +
  labs(x="Molecular Model Time")
```


```{r}
dat <- merge(secretory_model_phenotype,
             combat_phenotype %>% select(sample_id, transformed_time_2),
             by="sample_id")
ggplot(dat, aes(x=pod, y=transformed_time_2)) +
  geom_point() +
  scale_x_continuous(breaks=1:14) +
  scale_y_continuous(breaks=seq(0, 100, by=10)) +
  labs(x="Molecular Model Time", y="Pathology POD")
```


```{r}
dat <- merge(secretory_model_phenotype,
             combat_phenotype %>% select(sample_id, transformed_time_2),
             by="sample_id")
ggplot(dat %>% filter(transformed_time_2 > -50), aes(x=best_estimate, y=transformed_time_2)) +
  geom_point() +
  scale_x_continuous(breaks=1:14) +
  scale_y_continuous(breaks=seq(0, 100, by=10)) +
  labs(y="Molecular Model Time", x="POD from Secretory Molecular Model")
```


```{r}
# Remove prolif samples
dat <- merge(secretory_model_phenotype,
             combat_phenotype %>% select(sample_id, transformed_time_2),
             by="sample_id")
ggplot(dat %>% filter(transformed_time_2 > 50), aes(x=best_estimate, y=transformed_time_2)) +
  geom_point() +
  labs(y="Molecular Model Time", x="POD from Secretory Molecular Model")
```

```{r}
saveRDS(dat, file="cache/fig_2ci_data.rds")
```


```{r}
dat <- combat_phenotype %>% 
  mutate(secretory_estimate=secretory_estimates[sample_id]) %>%
  select(sample_id, transformed_time_2, secretory_estimate)

ggplot(dat, aes(x=transformed_time_2, y=secretory_estimate)) +
  geom_point() +
  scale_x_continuous(breaks=seq(0, 100, by=10)) +
  labs(x="Molecular Model Time", y="POD estimate from Secretory Molecular Model")
```

-----

# Transformed time to secretory day

```{r}
# Remove proliferaive samples
pheno <- merge(secretory_model_phenotype,
               combat_phenotype %>% select(sample_id, transformed_time_2),
               by="sample_id") %>%
  filter(transformed_time_2 > 60) %>%
  arrange(transformed_time_2)

ggplot(pheno, aes(x=transformed_time_2, y=best_estimate)) +
  geom_point() +
  scale_y_continuous(breaks=1:14) +
  labs(x="Molecular Model Time", y="POD from Secretory Molecular Model")
```

```{r}
saveRDS(pheno, file="cache/fig_2cii_data.rds")
```


```{r}
# mod <- lowess(pheno$best_estimate, pheno$transformed_time_2)
# mod <- loess(best_estimate ~ transformed_time_2, pheno)
# f <- splinefun(x=mod$x, y=mod$y)
mod <- gam(best_estimate ~ s(transformed_time_2, bs="cr", k=5), data=pheno, gamma=1)
# plot(mod)
pheno <- pheno %>% mutate(new_pod=predict(mod, pheno))

ggplot(pheno, aes(x=transformed_time_2, y=best_estimate)) +
  geom_point(aes(color=study)) +
  geom_line(aes(y=new_pod), alpha=0.5) +
  scale_y_continuous(breaks=1:14) +
  labs(x="Molecular Model Time", y="POD from Secretory Molecular Model")
```

```{r}
time_range <- 60:100
transformed_time_to_pod <- round(predict(mod, data.frame(transformed_time_2=time_range)))
names(transformed_time_to_pod) <- time_range
transformed_time_to_pod
```

-----

# Array model EDA

```{r}
ggplot(array_combat_phenotype, aes(x=transformed_time_2, y=cycle_stage_reassigned_prolif)) +
  geom_jitter(height=0.1, width=0) +
  scale_y_discrete(limits = factor(c(NA, 7:1))) +
  scale_x_continuous(breaks=seq(0, 100, by=10)) +
  labs(x="Molecular Model Time")

ggplot(array_combat_phenotype, aes(x=transformed_time_2, y=new_cycle_stage)) +
  geom_jitter(height=0.1, width=0) +
  scale_y_discrete(limits = factor(c(NA, 7:1))) +
  scale_x_continuous(breaks=seq(0, 100, by=10)) +
  labs(x="Molecular Model Time")
```


```{r}
dat <- merge(array_secretory_model_phenotype,
             array_combat_phenotype %>% select(sample_id, transformed_time_2),
             by="sample_id")
ggplot(dat, aes(x=pod, y=transformed_time_2)) +
  geom_point() +
  scale_x_continuous(breaks=1:14) +
  scale_y_continuous(breaks=seq(0, 100, by=10)) +
  labs(x="Molecular Model Time", y="Pathology POD")
```


```{r}
dat <- merge(array_secretory_model_phenotype,
             array_combat_phenotype %>% select(sample_id, transformed_time_2),
             by="sample_id")
ggplot(dat %>% filter(transformed_time_2 > -50), aes(x=best_estimate, y=transformed_time_2)) +
  geom_point() +
  scale_x_continuous(breaks=1:14) +
  scale_y_continuous(breaks=seq(0, 100, by=10)) +
  labs(y="Molecular Model Time", x="POD from Secretory Molecular Model")
```

```{r}
# Remove proliferaive samples
array_pheno <- merge(array_secretory_model_phenotype,
               array_combat_phenotype %>% select(sample_id, transformed_time_2),
               by="sample_id") %>%
  filter(transformed_time_2 > 60) %>%
  arrange(transformed_time_2)

ggplot(array_pheno, aes(x=transformed_time_2, y=best_estimate)) +
  geom_point() +
  scale_y_continuous(breaks=1:14) +
  labs(x="Molecular Model Time", y="POD from Secretory Molecular Model")
```



```{r}
# Remove prolif samples
dat <- merge(array_secretory_model_phenotype,
             array_combat_phenotype %>% select(sample_id, transformed_time_2),
             by="sample_id")
ggplot(dat %>% filter(transformed_time_2 > 50), aes(x=best_estimate, y=transformed_time_2)) +
  geom_point() +
  labs(y="Molecular Model Time", x="POD from Secretory Molecular Model")
```


```{r}
dat <- array_combat_phenotype %>% 
  mutate(secretory_estimate=array_secretory_estimates[sample_id]) %>%
  select(sample_id, transformed_time_2, secretory_estimate)

ggplot(dat, aes(x=transformed_time_2, y=secretory_estimate)) +
  geom_point() +
  scale_x_continuous(breaks=seq(0, 100, by=10)) +
  labs(x="Molecular Model Time", y="POD estimate from Secretory Molecular Model")
```

## Transformed time

```{r}
# Remove proliferaive samples
array_pheno <- merge(array_secretory_model_phenotype,
               array_combat_phenotype %>% select(sample_id, transformed_time_2),
               by="sample_id") %>%
  filter(transformed_time_2 > 60) %>%
  arrange(transformed_time_2)

ggplot(array_pheno, aes(x=transformed_time_2, y=best_estimate)) +
  geom_point() +
  scale_y_continuous(breaks=1:14) +
  labs(x="Molecular Model Time", y="POD from Secretory Molecular Model")
```

```{r}
mod <- gam(best_estimate ~ s(transformed_time_2, bs="cr", k=5), data=array_pheno, gamma=1)
# plot(mod)
array_pheno <- array_pheno %>% mutate(new_pod=predict(mod, array_pheno))

ggplot(array_pheno, aes(x=transformed_time_2, y=best_estimate)) +
  geom_point(aes(color=study)) +
  geom_line(aes(y=new_pod), alpha=0.5) +
  scale_y_continuous(breaks=1:14) +
  labs(x="Molecular Model Time", y="POD from Secretory Molecular Model")
```

```{r}
time_range <- 60:100
array_transformed_time_to_pod <- round(
  predict(mod, data.frame(transformed_time_2=time_range)))
names(array_transformed_time_to_pod) <- time_range
array_transformed_time_to_pod
```

-----

# Compare RNA and array model


```{r}
rna_array_time_estimate <- inner_join(
  combat_phenotype %>% 
    select(sample_id, transformed_time_2) %>%
    rename(rna_time="transformed_time_2"),
  array_combat_phenotype %>% 
    filter(! is.na(transformed_time_2)) %>%
    select(sample_id, transformed_time_2) %>%
    rename(array_time="transformed_time_2"))
```

```{r}
rna_array_time_estimate %>% nrow
```


```{r}
ggplot(rna_array_time_estimate, aes(x=rna_time, y=array_time)) +
  geom_point() +
  geom_abline(linetype="dashed", color="red") +
  theme_bw()
```

```{r}
saveRDS(rna_array_time_estimate, file="cache/fig3a.rds")
```

```{r}
rna_array_time_estimate %>% arrange(desc(abs(array_time - rna_time))) %>% head

# Change 0 -> 100 for array time for sample X210427 before calculating correlation
tmp <- rna_array_time_estimate %>%
  mutate(array_time=ifelse(array_time == 0, 100, array_time))
cor(tmp$rna_time,
    tmp$array_time)
```

```{r}
combat_phenotype %>% filter(sample_id %in% c("X210474", "X210131"))
```

-----

# Compare model to hormone assay

```{r}
dat <- inner_join(hormone_info,
                  combat_phenotype %>% select(sample_id, transformed_time_2)) %>%
  rename(model_time_estimate="transformed_time_2")
```

```{r}
ggplot(dat, aes(x=model_time_estimate, y=p4_ng_ml)) +
  geom_point() +
  theme_bw()
```

```{r}
saveRDS(dat, file="cache/fig3bc.rds")
```

```{r}
ggplot(dat, aes(x=model_time_estimate, y=estradiol_pg_m_l)) +
  geom_point() +
  theme_bw()
```


-----

# Session Info

```{r}
devtools::session_info()
```
