---
title: "Secretory model"
author: "Jessica Chung"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
    toc_depth: 4
---

Fit a secretory model using POD days.

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=TRUE, message=TRUE, error=TRUE, echo=TRUE, results="hold")
knitr::opts_knit$set(root.dir = "..")
options(digits=4)
options(width=120)
Sys.setenv(TZ = "Australia/Melbourne")
```

-----

# Load

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(sva)
library(splines)
```

```{r}
sample_info <- readRDS("data/tidy_data/sample_info.rds")
combat_exprs <- readRDS("data/array_data/combined_combat_exprs_corrected.rds")
pval <- readRDS("data/array_data/pval.rds")
probe_info <- readRDS("data/array_data/illumina_v4_annotation.rds")
```

```{r}
s1_secretory_pheno <- sample_info %>%
  filter(str_detect(sample_id, "^X")) %>%
  mutate(hr=as.numeric(original_histology_dating_pod_or_helene_rees),
         vo=as.numeric(vanessa_obers_pathology_pod)) %>%
  rowwise() %>%
  mutate(pod=mean(c(hr, vo), na.rm=TRUE)) %>%
  ungroup() %>%
  filter(is.finite(pod)) %>%
  select(sample_id, pod) %>%
  mutate(study="study_1")
s2_secretory_pheno <- sample_info %>% 
  filter(! is.na(consensus_pod_urs_only)) %>%
  mutate(pod=as.numeric(consensus_pod_urs_only)) %>%
  select(sample_id, pod) %>%
  mutate(study="study_2")
```

-----

# Spline model

```{r}
fit_spline_model <- function(y, x, spline_k=6, spline_fx=FALSE, spline_bs="cc", 
                             gamma=1, predict_range=seq(0,28,by=0.1), 
                             weights=NULL, knots=NULL, return_coefs=FALSE,
                             return_fit=TRUE) {
  
  fit <- gam(y ~ s(x, bs=spline_bs, k=spline_k, fx=spline_fx), 
             knots=knots, weights=weights, gamma=gamma)
  fit_summary <- summary(fit)
  
  pred <- predict(fit, newdata=data.frame(x=predict_range))
  pred <- data.frame(cycle_time=predict_range, pred=pred)
  
  results <- list(pred=pred, 
                  edf=round(fit_summary$edf, 3),
                  R2=round(fit_summary$r.sq, 4),
                  dev_exp=round(fit_summary$dev.expl, 4),
                  s_table=fit_summary$s.table)
  if (return_coefs) results$coefs <- fit$coefficients
  if (return_fit) results$fit <- fit
  return(results)
}

plot_spline_model <- function(spline_list, y, x, gene_name="", alpha_point=1,
                              alpha_line=0.5, jitter_height=0, jitter_width=0.05, 
                              plot=TRUE) {
  dat <- data.frame(exprs=y, cycle_time=x)
  g <- ggplot(dat, aes(x=cycle_time, y=exprs)) +
    geom_jitter(height=jitter_height, width=jitter_width, alpha=alpha_point) +
    geom_line(spline_list$pred, mapping=aes(x=cycle_time, y=pred), alpha=alpha_line) +
    labs(title=sprintf("%s | R^2 = %0.3f | edf = %0.2f", 
                       gene_name, spline_list$R2, spline_list$edf))
  if (! plot) return(g)
  print(g)
}
```

-----

# Fit secretory day

```{r}
subset_pheno <- rbind(s1_secretory_pheno, s2_secretory_pheno) %>%
  filter(sample_id %in% colnames(combat_exprs))
table(subset_pheno$pod)
```

```{r}
ggplot(subset_pheno, aes(x=pod, fill=study)) +
  geom_histogram(binwidth=0.5)
```

## Get probes

```{r}
stopifnot(probe_info$IlluminaID == rownames(pval))
probe_info <- probe_info %>% 
  mutate(p_detected=rowMeans(pval < 0.05),
         pass_quality=str_detect(ProbeQuality, "Perfect|Good"),
         pass_detect=p_detected > 0.2)

ok <- probe_info %>%
  filter(pass_quality & pass_detect) %>%
  pull(IlluminaID)
length(ok)

combat_exprs <- combat_exprs[ok,]
```

## Fit spline

```{r}
subset_cycle_time <- as.numeric(subset_pheno$pod)
subset_cycle_range <- seq(1, 14, by=0.1)

exprs <- combat_exprs[,subset_pheno$sample_id]
probes <- rownames(combat_exprs)
gene_models <- lapply(probes, function(p) {
  fit_spline_model(y=exprs[p,], x=subset_cycle_time, 
                   spline_k=3, gamma=2, spline_bs="cr",
                   predict_range=subset_cycle_range, weights=NULL,
                   return_fit=FALSE)
})
names(gene_models) <- probes
```


```{r}
# Get expected values for each cycle day for each probe
expected_exprs <- sapply(probes, function(p) gene_models[[p]]$pred$pred) %>% 
  t %>% magrittr::set_colnames(paste0("day_", subset_cycle_range))

# Get probe R^2 values
r2 <- sapply(probes, function(p) gene_models[[p]]$R2)

# Get df for models
spline_edf <- sapply(probes, function(p) gene_models[[p]]$edf)
table(cut(spline_edf, breaks = 5))

# Get deviance explained
dev_exp <- sapply(probes, function(p) gene_models[[p]]$dev_exp)
cor(r2, dev_exp)

# Get coefficients
#coefs <- sapply(probes, function(p) gene_models[[p]]$coefs) %>% t
#colnames(coefs) <- str_remove_all(colnames(coefs), "[()]")

# Get p-values
pvals <- sapply(probes, function(p) gene_models[[p]]$s_table[1,"p-value"])

model_df <- data.frame(probe_id=probes, r2=r2, spline_edf=spline_edf, 
                       dev_exp=dev_exp, p=pvals,
                       stringsAsFactors=FALSE)
```


```{r}
ggplot(model_df %>% head(1000), aes(x=spline_edf, y=r2)) +
  geom_point(alpha=0.2, size=1)

ggplot(model_df %>% head(1000), aes(x=p, y=r2)) +
  geom_point(alpha=0.2, size=1) +
  scale_x_log10()
```


```{r results="markup"}
# Examine some genes

# Linear
g <- model_df %>% filter(spline_edf %>% between(1, 1)) %>% head(1)
g %>% t
plot_spline_model(gene_models[[g$probe_id]], x=subset_cycle_time, y=exprs[g$probe_id,], gene_name=g$probe_id)

# Medium spline_edf but low r2
g <- model_df %>% filter(spline_edf > 1.5, r2 < 0.2) %>% head(1)
g %>% t
plot_spline_model(gene_models[[g$probe_id]], x=subset_cycle_time, y=exprs[g$probe_id,], gene_name=g$probe_id)

# Okay fit
g <- model_df %>% filter(r2 %>% between(0.20, 0.22)) %>% head(1)
g %>% t
plot_spline_model(gene_models[[g$probe_id]], x=subset_cycle_time, y=exprs[g$probe_id,], gene_name=g$probe_id)

# High r2
g <- model_df %>% arrange(desc(r2)) %>% head(1)
g %>% t
plot_spline_model(gene_models[[g$probe_id]], x=subset_cycle_time, y=exprs[g$probe_id,], gene_name=g$probe_id)
```

## Get best day estimate

```{r}
# Get best estimate
pheno <- sample_info %>% filter(sample_id %in% colnames(combat_exprs))
fit1_best_estimate <- sapply(pheno$sample_id, function(s) {
  sweep(x=expected_exprs, MARGIN=1, STATS=combat_exprs[,s]) %>% 
    `^`(2) %>% colSums %>% which.min %>% names %>% str_replace("day_", "") %>%
    as.numeric
})
```


```{r}
subset_pheno <- subset_pheno %>%
  mutate(best_estimate=fit1_best_estimate[sample_id])

ggplot(subset_pheno, aes(x=pod, y=best_estimate, color=study)) +
  geom_jitter(height=0, width=0) +
  labs(x="Cycle stage from pathology", 
       y="Best estimate of cycle day using model",
       title="Pathology cycle stage vs molecular model cycle day prediction") +
  geom_abline(linetype="dashed", alpha=0.5)
```

-----

# Save

```{r}
secretory_model_phenotype <- subset_pheno
```

```{r}
# Save
unique_id <- "2020-12-02"
saveRDS(secretory_model_phenotype,
        file=sprintf("data/tidy_data/array_secretory_model_%s.rds", unique_id))
saveRDS(fit1_best_estimate,
        file=sprintf("cache/array_secretory_model_estimates_%s.rds", unique_id))
```

-----

# Session Info

```{r}
devtools::session_info()
```


